<?php
require 'dompdf/vendor/autoload.php'; // Sesuaikan path ke dompdf Anda
include 'koneksi.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// Pastikan ada vessel_id yang dikirim
$vessel_id = isset($_GET['vessel_id']) ? $_GET['vessel_id'] : '';

if (!$vessel_id) {
    die("ID Vessel tidak ditemukan.");
}

// 1. Ambil data Kapal & Tanggal dari URL
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : '';
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : '';

$v_query = mysqli_query($conn, "SELECT * FROM vessels WHERE id = '$vessel_id'");
$vessel = mysqli_fetch_assoc($v_query);

// 2. MODIFIKASI QUERY SQL (Bagian ini yang paling penting cuy!)
$sql = "SELECT l.*, i.part_name, i.part_number, m.component_name, s.sub_component_name 
        FROM stock_logs l 
        JOIN inventory i ON l.inventory_id = i.id 
        JOIN main_components m ON i.main_component_id = m.id 
        LEFT JOIN sub_components s ON i.sub_component_id = s.id 
        WHERE i.vessel_id = '$vessel_id'";

// Cek kalau user pilih tanggal, masukin ke query
if ($start_date && $end_date) {
    $sql .= " AND l.created_at BETWEEN '$start_date 00:00:00' AND '$end_date 23:59:59'";
}

$sql .= " ORDER BY l.created_at DESC";
$query = mysqli_query($conn, $sql);

// 3. Bangun struktur HTML untuk PDF
$html = '
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: "Helvetica", sans-serif; color: #1e293b; font-size: 11px; margin: 0; padding: 0; }
        .header { text-align: center; margin-bottom: 25px; border-bottom: 2px solid #0f172a; padding-bottom: 10px; }
        .report-title { font-size: 18px; font-weight: bold; text-transform: uppercase; margin: 0; color: #0f172a; }
        .report-subtitle { font-size: 11px; color: #64748b; margin-top: 5px; }
        
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 2px 0; }
        .label { color: #64748b; width: 100px; }
        .value { font-weight: bold; }

        table.main-table { width: 100%; border-collapse: collapse; }
        table.main-table th { 
            background-color: #f8fafc; 
            color: #475569; 
            padding: 10px 8px; 
            border: 1px solid #e2e8f0; 
            text-align: left; 
            text-transform: uppercase; 
            font-size: 9px;
            letter-spacing: 0.05em;
        }
        table.main-table td { 
            padding: 8px; 
            border: 1px solid #e2e8f0; 
            vertical-align: top;
        }
        
        .status-in { color: #16a34a; font-weight: bold; }
        .status-out { color: #dc2626; font-weight: bold; }
        .bg-gray { background-color: #f8fafc; }
        .fw-bold { font-weight: bold; }
        
        .footer { position: fixed; bottom: -30px; left: 0; right: 0; height: 30px; text-align: right; font-size: 9px; color: #94a3b8; }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>
    <div class="footer">
        Generated by Ship Management System | Page <span class="page-number"></span>
    </div>

    <div class="header">
        <h1 class="report-title">Stock Movement Report</h1>
        <p class="report-subtitle">Historical log of sparepart adjustment for vessel operations</p>
    </div>

    <table class="info-table">
        <tr>
            <td class="label">Unit / Vessel</td>
            <td class="value">: ' . strtoupper($vessel['vessel_name']) . '</td>
            <td class="label" style="text-align:right;">Export Date</td>
            <td class="value" style="text-align:right;">: ' . date('d F Y') . '</td>
        </tr>
        <tr>
            <td class="label">Vessel Type</td>
            <td class="value">: ' . $vessel['vessel_type'] . '</td>
            <td class="label" style="text-align:right;">Period</td>
            <td class="value" style="text-align:right; color: #dc2626;">: ' . ($start_date ? date('d/m/Y', strtotime($start_date)) . ' - ' . date('d/m/Y', strtotime($end_date)) : 'All Time') . '</td>
        </tr>
    </table>

    <table class="main-table">
        <thead>
            <tr>
                <th width="12%">Date & Time</th>
                <th width="13%">Main Component</th>
                <th width="10%">Sub Component</th>
                <th width="15%">Part Description</th>
                <th width="8%">Type</th>
                <th width="7%">Qty</th>
                <th width="7%">Prev</th>
                <th width="7%">Final</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>';

if (mysqli_num_rows($query) > 0) {
    while($row = mysqli_fetch_assoc($query)) {
        $is_in = ($row['type'] == 'IN');
        $type_text = $is_in ? 'STOCK IN' : 'STOCK OUT';
        $type_class = $is_in ? 'status-in' : 'status-out';
        $qty_prefix = $is_in ? '+' : '-';
        $sub_component = !empty($row['sub_component_name']) ? $row['sub_component_name'] : '-';

        $html .= '
            <tr>
                <td>' . date('d/m/Y', strtotime($row['created_at'])) . '<br><small style="color:#64748b;">' . date('H:i', strtotime($row['created_at'])) . ' WIB</small></td>
                <td><strong>' . $row['component_name'] . '</strong></td>
                <td>' . $sub_component . '</td> 
                <td>' . $row['part_name'] . '<br><small style="color:#64748b;">' . $row['part_number'] . '</small></td>
                <td class="' . $type_class . '">' . $type_text . '</td>
                <td style="text-align:center;" class="' . $type_class . '">' . $qty_prefix . $row['qty_change'] . '</td>
                <td style="text-align:center;">' . $row['previous_qty'] . '</td>
                <td style="text-align:center;" class="bg-gray fw-bold">' . $row['current_qty'] . '</td>
                <td style="font-size: 9px; color: #475569;">' . htmlspecialchars($row['remarks']) . '</td>
            </tr>';
    }
} else {
    $html .= '<tr><td colspan="9" style="text-align:center; padding: 40px; color: #94a3b8;">No movement records found for the selected period.</td></tr>';
}

$html .= '
        </tbody>
    </table>
</body>
</html>';

// 4. Konfigurasi Dompdf
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

// 5. Output file PDF
$filename = "Report_" . str_replace(" ", "_", $vessel['vessel_name']) . "_" . ($start_date ? $start_date . "_to_" . $end_date : date('Ymd')) . ".pdf";
$dompdf->stream($filename, array("Attachment" => false));
?>